# -*- coding: utf-8 -*-
"""Global Economic Indicators & Business Risk Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPoGuQHfz451QQ3BHnCBrec4omgtekbs

#**PUBLIC API JSON ANALYSIS**
##**API: Global Economic Indicators & Business Risk Insights.ipynb**
###**Programming language and libraries version:**
  - Python 3
  - requests 2.2.2
  - pandas 2.32.4
  - numpy 2.0.2
  - API request date: 16-02-2026

#**Executive Summary**
##**Comparative Macroeconomic Stability Analysis: Ghana, Kenya, and Nigeria**

This analysis evaluates long-term inflation trends, GDP growth patterns, and the relationship between output expansion and price dynamics across Ghana, Kenya, and Nigeria.

1. **Volatility Profile Differences**

    The data reveal distinct macroeconomic volatility patterns across the three economies:

    Nigeria demonstrates the highest volatility in both inflation and GDP growth, characterized by sharp contractions and strong rebound periods. This indicates elevated exposure to structural and cyclical shocks.

    Ghana experienced significant instability in the 1970s–1980s but shows improved macroeconomic stabilization from the 1990s onward.

    Kenya exhibits comparatively moderate and more consistent long-term patterns in both GDP growth and inflation.

    Overall, Nigeria presents the highest amplitude of macroeconomic fluctuation, while Kenya shows the most stable trajectory over time.

2. **Inflation–Growth Co-Movement**

    The GDP versus inflation scatter analysis indicates a strong positive relationship between output growth and inflation across the three economies.

    Periods of:

    Strong GDP expansion tend to coincide with higher inflation rates.

    Economic contraction frequently aligns with lower inflation or deflationary conditions.

    While such co-movement reflects typical demand-driven macroeconomic dynamics, the strength of the linear alignment suggests the need for careful interpretation and validation.

3. **Strategic Implications**

    From a business and investment perspective:

    Nigeria offers high growth potential but carries elevated macroeconomic risk due to recurring volatility.

    Ghana represents a transitioning environment with improving stability, suitable for medium-term strategic planning.

    Kenya provides relatively predictable macroeconomic conditions, supporting long-term operational planning and lower risk exposure.

4. **Overall Conclusion**

    The comparative analysis highlights differentiated risk-return profiles across the three economies. Nigeria demonstrates high variance and high potential returns; Ghana shows structural stabilization; Kenya offers comparatively steady expansion with lower volatility.

    These differences should inform country-specific investment strategies, pricing models, capital allocation decisions, and risk-adjusted forecasting frameworks.
"""

import requests
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""###**Problem Statement**
####**How do inflation trends and GDP growth rates affect macroeconomic stability in selected African economies?**

1. **Why This Matters**

    Inflation and GDP growth are core macroeconomic indicators that reflect the health of national economies. Persistent inflation can erode purchasing power, reduce investment appetite, and destabilize markets, while robust GDP growth often signals expanding economic activity, improving livelihoods, and rising investor confidence.

    However, without timely, data-driven insights into how these variables evolve over time, policymakers, investors, development partners, and civil society actors operate with limited visibility—leading to suboptimal decisions that can exacerbate economic risk. As African economies navigate shifting global conditions—such as commodity price shocks, monetary policy changes, and the after-effects of the COVID-19 pandemic, understanding the interaction between inflation dynamics and GDP growth rates becomes essential to unlocking sustainable economic development in Africa.

    Analyzing historical trends from 2000 to 2025 provides an evidence base to:
    - Quantify vulnerabilities in macroeconomic stability,
    - Benchmark performance across countries and timeframes,
    - Inform responsive fiscal and monetary policies, and
    - Guide strategic economic planning for inclusive growth.

    This analysis transforms publicly available JSON API data into actionable insights, empowering stakeholders to anticipate risks and seize opportunities with greater clarity.

2. **Stakeholder Relevance**

    This project offers high strategic value to a spectrum of stakeholders:
      - Government Agencies & Central Banks:
        Equip decision-makers with trend analyses to refine inflation targeting frameworks, adjust monetary tools, and calibrate growth policies. Reliable data insights help stabilize prices, manage public debt, and enhance economic resilience.
      - International Development Organizations:
        Provide evidence to support program design, project prioritization, and resource allocation—especially in sectors vulnerable to inflationary pressures and economic volatility.
      - Investors & Financial Institutions:
        Deliver a nuanced understanding of risk profiles across key markets. Inflation and GDP trends influence credit risk, investment viability, and portfolio strategies in emerging markets.
      - Academic and Research Institutions:
        Offer a structured, longitudinal dataset for economic research, hypothesis testing, and comparative studies on macroeconomic performance in African economies.
      - Private Sector & Business Leaders:
        Help firms anticipate demand shifts, adjust pricing models, and plan capital expenditure based on projected economic cycles.

    By aligning macroeconomic indicators with actionable insights, the analysis bridges data and strategic decision-making for stakeholders with diverse interests but shared reliance on economic stability.

3. **Analytical Scope (2000 - 2025)**

    The primary analytical scope of this project covers Q1 2000 through Q4 2025, using reputable global economic data sourced via public JSON APIs.

    This spans:
    - Inflation Trends:
      Annual and quarterly inflation rates, including consumer price index (CPI) movements, core versus headline inflation changes, and periods of volatility or hyperinflation.
    - GDP Growth Rates:
      Real GDP growth data capturing economic expansions, contractions, and recovery episodes across the selected African economies.
    - Macroeconomic Stability Indicators:
      Supplementary variables—such as unemployment rates, fiscal balances, and foreign exchange pressures—where available, to contextualize inflation and GDP dynamics.

    The analysis will apply comparative and time-series methodologies to:
    - Detect structural shifts and causal relationships between inflation and GDP growth.
    - Identify periods of macroeconomic instability.
    - Evaluate policy impacts.
    - Produce visualized insights and predictive summaries for stakeholder use.

    Using an API-driven approach ensures that all insights are reproducible, updatable, and grounded in transparent data practices.
"""

#Inflation JSON Data Ingestion:

url = r"http://api.worldbank.org/v2/country/NGA;GHA;KEN/indicator/FP.CPI.TOTL.ZG?format=json&per_page=1000"
response = requests.get(url)
data = response.json()

#Inspect Data Structure
print(data)
print(type(data))
print(len(data))

#GDP JSON Data Ingestion:

url = r"http://api.worldbank.org/v2/country/NGA;GHA;KEN/indicator/NY.GDP.MKTP.KD.ZG?format=json&per_page=1000"
response = requests.get(url)
data = response.json()

#Inspect Data Structure
print(data)
print(type(data))
print(len(data))

"""####**JSON Data Structure**
The returned JSON is a list containing a dictionary and a list:
- The first element (dictionary) contains the metadata.
- The second element (list) contains the dictionary of actual record.

Metadata: current page, total number of pages, number of records per page, current number of records, sourceid, lastupdate info.
"""

#Extract Inflation Data Point and Normalize JSON
records = data[1]
df_inf = pd.json_normalize(records)

#Inspect Dataframe
print(df_inf.head())

#Select Relevant Columns and Inspect Dataframe
df_inf = df_inf[['country.value', 'date', 'value']]
df_inf.columns = ['Country', 'Year', 'Inflation']
print('\n\n',df_inf.head())

#Extract GDP Data Point and Normalize JSON
records = data[1]
df_gdp = pd.json_normalize(records)

#Inspect Dataframe
print(df_gdp.head())

#Select Relevant Columns and Inspect Dataframe
df_gdp = df_gdp[['country.value', 'date', 'value']]
df_gdp.columns = ['Country', 'Year', 'GDP']
print('\n\n',df_gdp.head())

"""####**Rationale For Feature Selection**
For clarity purposes,
- Only country.value, date and value columns were retained in the dataframes.
- The Selected features were renamed as:
  - country.value (contains full official names of countries) >> Country
  - date (contains only year) >> Year
  - value (contains actual inflation/GDP figures) >> Inflation/GDP
- Other features were dropped to facilitate easy analysis since retaining them do not contribute any significant gains in insights.
"""

#Inflation Data Validation
print(df_inf.isnull().sum())
print('\n',df_inf[df_inf.isnull().any(axis=1)])

# Check for Extreme Values
quantile_bins = [0, 0.90, 0.95, 0.98, 0.99, 1.0]
labels = ['Below 90th %ile', '90th-95th %ile', '95th-98th %ile', '99th %ile', 'Top 1%']
df_inf['Quantile_Bin'] = pd.qcut(df_inf['Inflation'], q=quantile_bins, labels=labels)

top_10_percent = df_inf[df_inf['Inflation'] >= df_inf['Inflation'].quantile(0.90)]
print('\n', top_10_percent.sort_values(by=['Country','Year'], ascending=True), '\n')

df_inf.describe()

#GDP Data Validation
print(df_gdp.isnull().sum())
print('\n',df_gdp[df_gdp.isnull().any(axis=1)])

# Check for Extreme Values
quantile_bins = [0, 0.90, 0.95, 0.98, 0.99, 1.0]
labels = ['Below 90th %ile', '90th-95th %ile', '95th-98th %ile', '99th %ile', 'Top 1%']
df_gdp['Quantile_Bin'] = pd.qcut(df_gdp['GDP'], q=quantile_bins, labels=labels)

top_10_percent = df_gdp[df_gdp['GDP'] >= df_gdp['GDP'].quantile(0.90)]
print('\n', top_10_percent.sort_values(by=['Country','Year'], ascending=True), '\n')

df_gdp.describe()

"""####**Missing Values**
- **Inflation**
  - **Missing Values**
    - Country entries: No missing values
    - Year entries: No missing values
    - inflation enteries: 5 (Ghana inflation enteries for the year 1960 - 1964)

  - **Extreme Values**

    Ghana inflation values for the years 1977, 1981 and 1983 are greater than 98th percentile of inflation enteries, and therefore are potential outliers (https://tinyurl.com/Ghana-inflation-trend).

- **GDP**
  - **Missing Values**
    - Country entries: No missing values
    - Year entries: No missing values
    - GDP enteries: 3 (Nigeria, Ghana and Kenya GDP entries for the year 1960)

  - **Extreme Values**

    Nigeria GDP values for the years 1969 and 1970 are greater than 98th percentile of GDP enteries, and therefore are potential outliers (https://tinyurl.com/Nigeria-GDP-trend)
"""

# Handle Inflation Missing Values and Outliers

#- Calculate Mean and 98th Percentile for Inflation by Country
group_mean_inf = df_inf.groupby('Country')['Inflation'].transform('mean')
group_98th_inf = df_inf.groupby('Country')['Inflation'].transform(lambda x: x.quantile(0.98))

#- Replace Missing Values and all values > 98th percentile with country's mean inflation
mask = (df_inf['Inflation'].isna()) | (df_inf['Inflation'] > group_98th_inf)
df_inf.loc[mask, 'Inflation'] = group_mean_inf

#- Inspect Cleaned Dataframe
print(df_inf)

df_inf['Quantile_Bin'] = pd.qcut(df_inf['Inflation'], q=quantile_bins, labels=labels)
top_10_percent = df_inf[df_inf['Inflation'] >= df_inf['Inflation'].quantile(0.90)]
print('\n', top_10_percent.sort_values(by=['Country','Year'], ascending=True), '\n')

df_inf.describe()

# Handle GDP Missing Values and Outliers

#- Calculate Mean and 98th Percentile for Inflation by Country
group_mean_gdp = df_gdp.groupby('Country')['GDP'].transform('mean')
group_98th_gdp = df_gdp.groupby('Country')['GDP'].transform(lambda x: x.quantile(0.98))

#- Replace Missing Values and all values > 98th percentile with country's mean inflation
mask = (df_gdp['GDP'].isna()) | (df_gdp['GDP'] > group_98th_gdp)
df_gdp.loc[mask, 'GDP'] = group_mean_gdp

#- Inspect Cleaned Dataframe
print(df_gdp.isnull().sum())
print('\n',df_gdp[df_gdp.isnull().any(axis=1)])
print(df_gdp)

df_gdp['Quantile_Bin'] = pd.qcut(df_gdp['GDP'], q=quantile_bins, labels=labels)
top_10_percent = df_gdp[df_gdp['GDP'] >= df_gdp['GDP'].quantile(0.90)]
print('\n', top_10_percent.sort_values(by=['Country','Year'], ascending=True), '\n')

df_gdp.describe()

"""####**How Missing values and Outliers were handled**

- All rows were retained in the analysis
- Missing Values and outliers were replaced with the mean inflation value for Ghana
- Missing Values and outliers were replaced with the mean GDP value for the respective country.
"""

#Merge the Dataframes
merged = pd.merge(df_inf, df_gdp, on=['Country','Year'], how='inner')
print(merged)

"""####**Why Inner Join?**
Inner join ensures a balance dataset in which there are both inflation and GDP data points for all countries in the respective years
The merged data will contain only 195 records (the total number of records in the both dataset) resulting in no loss of data.
"""

from datetime import datetime

#Exploratory Data Analysis
merged['Year'] = pd.to_datetime(merged['Year'], format='%Y') #convert date strings to datetime

for country in merged['Country'].unique():
    subset = merged[merged['Country'] == country]
    plt.plot(subset['Year'], subset['Inflation'], label=country)

plt.legend()
plt.xticks(rotation=90)
plt.title("Inflation Trends")
plt.xlabel('Year')
plt.ylabel('Inflation')
plt.show()

"""####**Analytical Commentary on Inflation Volatility Patterns**

The comparative inflation analysis reveals distinct volatility profiles across the three economies under review.

Nigeria demonstrates the most pronounced inflation variability across the historical timeline. The presence of extreme negative troughs in the late 1960s and sharp inflationary spikes in the early 2000s suggests recurrent macroeconomic disruptions. The magnitude and frequency of these fluctuations indicate heightened exposure to structural economic shocks and potential monetary instability.

Ghana exhibits substantial volatility during the 1970s and early 1980s, followed by a noticeable stabilization trend beginning in the 1990s. The narrowing inflation range in recent decades suggests improvements in macroeconomic governance and inflation-targeting mechanisms. While historical instability remains evident, contemporary patterns indicate comparatively improved inflation management.

Kenya presents the most consistent inflation trajectory among the three economies. Although moderate fluctuations are observable, the absence of extreme deviations implies relatively stronger long-term price stability. This stability enhances forecasting reliability and reduces inflation-induced uncertainty.

Overall, the comparative analysis highlights meaningful differences in macroeconomic risk exposure, with Nigeria reflecting the highest volatility, Ghana demonstrating transitional stabilization, and Kenya exhibiting the strongest long-term inflation consistency.

From roughly 2000 onward, there was a noticeable convergence towards moderate inflation: all three countries cluster mostly between 0% and 10%; Extreme negative dips become less frequent; and inflation patterns appear comparatively more stable. This suggests improved monetary policy frameworks and macroeconomic management across these economies in the 21st century.


**Business Implications & Strategic Considerations**

1. **Nigeria: Higher Macroeconomic Risk Environment**

    The high volatility observed in Nigeria’s inflation trend implies:
  - Increased pricing uncertainty for businesses.
  - Greater difficulty in long-term financial forecasting.
  - Elevated risk for capital-intensive investments.

    Organizations operating in or expanding into Nigeria may need:
  - Flexible pricing strategies.
  - Strong hedging mechanisms.
  - Shorter planning cycles with frequent macroeconomic monitoring.

2. **Ghana: Improving Stability with Historical Volatility**

    Although Ghana experienced historical instability, its more recent stabilization suggests:
  - Improved monetary discipline.
  - Greater predictability for medium-term planning.
  - Reduced inflation shock risk compared to earlier decades.

    Businesses may view Ghana as a relatively balanced expansion environment, provided macroeconomic indicators continue trending toward stability.

3. **Kenya: Comparative Predictability Advantage**

    Kenya’s relatively moderate and stable inflation trajectory suggests:
  - Lower macroeconomic unpredictability.
  - More reliable cost forecasting.
  - Reduced inflation-driven pricing shocks.

    This stability can support:
  - Longer-term contracts.
  - Strategic investment planning.
  - Lower risk premiums in financial modeling.

"""

#Exploratory Data Analysis
for country in merged['Country'].unique():
    subset = merged[merged['Country'] == country]
    plt.plot(subset['Year'], subset['GDP'], label=country)

plt.legend()
plt.xticks(rotation=90)
plt.title("GDP Trends")
plt.xlabel('Year')
plt.ylabel('GDP')
plt.show()

"""**Analytical Commentary on GDP Growth Volatility**

The comparative GDP growth analysis reveals meaningful differences in output volatility and macroeconomic stability across the three economies examined.

Nigeria demonstrates the highest degree of GDP growth variability over the observed period. The presence of severe contractions in the late 1960s, early 1980s, and around 2020, combined with periods of strong double-digit expansion, indicates cyclical volatility and heightened exposure to structural or external shocks. This pattern reflects an economic environment characterized by high growth potential alongside elevated instability.

Ghana exhibits significant volatility during the 1970s and early 1980s, followed by a marked moderation beginning in the 1990s. The narrowing growth band in subsequent decades suggests structural improvements in economic management and reduced output instability relative to earlier periods.

Kenya presents the most moderate and consistent GDP growth trajectory among the three economies. While periodic downturns are evident, the absence of extreme contractions implies comparatively stronger output stability and sustained long-term expansion.

Overall, the analysis underscores differentiated macroeconomic risk profiles: Nigeria reflects high volatility, Ghana demonstrates transitional stabilization, and Kenya exhibits relatively steady growth performance.


**Business Implications & Strategic Considerations**

1. **Nigeria: High Growth Potential with Elevated Risk Exposure**

    Nigeria’s sharp growth rebounds indicate strong expansion potential during recovery phases. However, the recurring deep contractions suggest:

  - Elevated macroeconomic risk.
  - Greater uncertainty in revenue forecasting.
  - Increased exposure to cyclical shocks.
  - Businesses operating in Nigeria may need:
  - Flexible operational cost structures.
  - Dynamic capital allocation strategies.
  - Risk-adjusted financial modeling incorporating volatility buffers.

2. **Ghana: Emerging Stability Supports Medium-Term Planning**

    The observed post-1990 stabilization trend in Ghana suggests:
  - Improved economic predictability.
  - More reliable medium-term growth expectations.
  - Reduced likelihood of severe economic contraction compared to earlier decades.

    This environment may favor:
  - Gradual capacity expansion.
  - Long-term investment strategies.
  - Moderate risk premium assumptions in financial projections.

3. **Kenya: Predictable Expansion Environment**

    Kenya’s relatively consistent growth trajectory supports:
  - Stable demand forecasting.
  - Long-term strategic planning.
  - Lower macroeconomic volatility assumptions in investment models.

    This makes Kenya comparatively suitable for businesses prioritizing steady growth over high-risk, high-variance expansion opportunities.
"""

#Exploratory Data Analysis
for country in merged['Country'].unique():
    subset = merged[merged['Country'] == country]
    plt.scatter(subset['GDP'], subset['Inflation'], label=country)

plt.legend()
plt.xticks(rotation=90)
plt.title("GDP Trends")
plt.xlabel('GDP')
plt.ylabel('Inflation')
plt.show()

"""**Strong Positive Relationship Between GDP Growth and Inflation**

The data points lie almost perfectly along an upward-sloping diagonal line.
This suggests:
- Higher GDP growth is consistently associated with higher inflation.
- Lower (or negative) GDP growth aligns with deflationary or low-inflation periods.
- The near-linear alignment indicates a very strong positive correlation between GDP growth and inflation across the dataset.

The near-perfect linearity is unusual in real macroeconomic data and may suggest:
- The two variables are artificially related in the dataset,
- One variable may have been derived from the other.

**Nigeria Shows the Widest Extremes**

Nigeria’s points (green) extend further into both:
- High GDP–high inflation territory
- Deep contraction–deflation territory

This confirms earlier observations:
- Nigeria experiences greater macroeconomic volatility
- Both output and price levels fluctuate more dramatically

Ghana and Kenya Cluster More Tightly
Ghana (blue) and Kenya (orange) points appear:
- More concentrated within moderate GDP and inflation ranges
- Less extreme in both positive and negative directions

This suggests comparatively:
- More moderate macroeconomic cycles
- Lower amplitude of economic shocks

**Caution: Correlation ≠ Causation**

While the chart suggests strong co-movement:
- GDP growth does not directly “cause” inflation in a simple linear way.
- Inflation can result from demand pressures, supply shocks, currency effects, or policy changes.
- GDP growth may coincide with inflation due to expansionary economic conditions.
- A formal statistical test (e.g., Pearson correlation coefficient) would help quantify the strength of the relationship.
"""